re-enable other parts. also go back to using system perl just easier

diff --git a/.github/workflows/macvim-buildtest.yaml b/.github/workflows/macvim-buildtest.yaml
--- a/.github/workflows/macvim-buildtest.yaml
+++ b/.github/workflows/macvim-buildtest.yaml
@@ -29,13 +29,12 @@ env:
 
   MAKE_BUILD_ARGS: LINK_AS_NEEDED=yes # In macOS we never over-specify link dependencies and we already check against external deps in smoketest. With LTO, linking takes a while, so we want to avoid using link.sh.
 
-  VERSIONER_PERL_VERSION: '5.40'  # macOS default Perl installation uses this to determine which one to use
-
   vi_cv_path_python: /Library/Frameworks/Python.framework/Versions/2.7/bin/python
   vi_cv_path_python3: "%s/bin/python3"
   vi_cv_path_plain_lua: "%s/bin/lua"
   vi_cv_path_ruby: "%s/opt/ruby/bin/ruby"
-  vi_cv_dll_name_perl: /opt/homebrew/lib/perl5/%s/darwin-thread-multi-2level/CORE/libperl.dylib
+  #vi_cv_dll_name_perl: /opt/homebrew/lib/perl5/%s/darwin-thread-multi-2level/CORE/libperl.dylib
+  vi_cv_dll_name_perl: /System/Library/Perl/%s/darwin-thread-multi-2level/CORE/libperl.dylib
   vi_cv_dll_name_python: /Library/Frameworks/Python.framework/Versions/2.7/Python
   vi_cv_dll_name_python3: /usr/local/Frameworks/Python.framework/Versions/Current/Python
   vi_cv_dll_name_python3_arm64: /opt/homebrew/Frameworks/Python.framework/Versions/Current/Python
@@ -84,7 +83,7 @@ jobs:
           xcodebuild -version
 
       # Set up, install, and cache gettext library for localization.
-      #
+
       - name: Set up gettext
         if: inputs.publish
         uses: ./.github/actions/universal-package
@@ -112,12 +111,6 @@ jobs:
           # Apple diff is broken. Use GNU diff instead. See http://github.com/vim/vim/issues/14056.
           brew install --quiet diffutils
 
-      - name: Grant microphone access for macos-14
-        if: inputs.os == 'macos-14'
-        run: |
-          # Temporary fix to fix microphone permission issues for macos-14 when playing sound.
-          sqlite3 $HOME/Library/Application\ Support/com.apple.TCC/TCC.db "INSERT OR IGNORE INTO access VALUES ('kTCCServiceMicrophone','/usr/local/opt/runner/provisioner/provisioner',1,2,4,1,NULL,NULL,0,'UNUSED',NULL,0,1687786159,NULL,NULL,'UNUSED',1687786159);"
-
       # Cache Python 2 to avoid downloading the installer every time. Legacy self-hosted runner
       # already has this installed. This cache shouldn't change over time as Python 2.7 is legacy.
       # Can't directly cache to /Library/Frameworks/Python.framework due to permission issues.
@@ -137,7 +130,11 @@ jobs:
 
           brew install --quiet ruby
           brew install --quiet lua
-          brew install --quiet perl
+
+          if [[ -d $(brew --prefix)/Cellar/perl ]]; then
+            # We just use system perl to reduce dependencies
+            brew unlink perl
+          fi
 
           echo "vi_cv_path_python3=$(printf $vi_cv_path_python3 $(brew --prefix))" >> $GITHUB_ENV
           echo "vi_cv_path_plain_lua=$(printf $vi_cv_path_plain_lua $(brew --prefix))" >> $GITHUB_ENV
@@ -155,7 +152,9 @@ jobs:
           #
           # This will be removed in the future as Python2 has been completely
           # unsupported for years.
-          if [ -d python27-cache ]; then
+          if [ -d /Library/Frameworks/Python.framework/Versions/2.7 ]; then
+            echo "Python 2.7 already installed"
+          elif [ -d python27-cache ]; then
             sudo cp -R python27-cache /Library/Frameworks/Python.framework/Versions/2.7
           else
             curl https://www.python.org/ftp/python/2.7.18/python-2.7.18-macosx10.9.pkg -o ~/Downloads/python-2.7.18-macosx10.9.pkg
@@ -326,87 +325,87 @@ jobs:
           make -C runtime/doc vimtags VIMEXE=../../${VIM_BIN}
           git diff --exit-code -- runtime/doc/tags
 
-#       - name: Check Xcode project compatibility version
-#         if: contains(matrix.extra, 'check-xcodeproj-compat')
-#         run: |
-#           # Confirm that the compatibility version of xcodeproj is correct and not outdated.
-#           rm -rf src/MacVim/MacVim_xcode8.xcodeproj
-#           make -C src macvim-xcodeproj-compat
-#           if ! git diff --exit-code -- src/MacVim/MacVim_xcode8.xcodeproj; then
-#             echo 'MacVim_xcode8.xcodeproj is outdated. Run "make -C src macvim-xcodeproj-compat" to re-generate it.'; false
-#           fi
-# 
-#       - name: Test MacVim
-#         id: test_macvim
-#         timeout-minutes: 10
-#         run: |
-#           make ${MAKE_BUILD_ARGS} -C src macvim-tests
-# 
-#       - name: Upload failed MacVim test results
-#         if: ${{ !cancelled() && failure() && steps.test_macvim.conclusion == 'failure' }}
-#         uses: ./.github/actions/test_macvim_artifacts
-# 
-#       - name: Build Vim test binaries
-#         run: |
-#           # Build the unit test binaries first. With link-time-optimization they take some time to link. Running them
-#           # separately de-couples them from the timeout in tests, and allow us to build in parallel jobs (since tests
-#           # can't run in parallel).
-#           NPROC=$(getconf _NPROCESSORS_ONLN)
-# 
-#           set -o verbose
-#           make ${MAKE_BUILD_ARGS} -j${NPROC} -C src unittesttargets
-# 
-#       - name: Test Vim
-#         if: startsWith(github.ref, 'refs/tags/') || !matrix.testgui
-#         timeout-minutes: 30
-#         run: |
-#           defaults delete org.vim.MacVim  # Clean up stale states
-#           # Currently we don't run any non-src tests, as syntax tests are fragile and prone to spamming escape codes.
-#           # This needs to be investigated and fixed upstream.
-#           # MacVim is unlikely to introduce breaking changes in runtime files anyway.
-#           make ${MAKE_BUILD_ARGS} -C src test
-# 
-#       - name: Test Vim (GUI)
-#         if: startsWith(github.ref, 'refs/tags/') || matrix.testgui
-#         timeout-minutes: 30
-#         run: |
-#           defaults delete org.vim.MacVim  # Clean up stale states
-#           make ${MAKE_BUILD_ARGS} -C src/testdir clean
-#           make ${MAKE_BUILD_ARGS} -C src testgui
-# 
-#       - name: Upload failed test files
-#         if: ${{ !cancelled() && failure() }}
-#         uses: ./.github/actions/test_artifacts
-# 
-#       - name: Build MacVim dmg image
-#         if: inputs.publish && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master')
-#         run: |
-#           # Use the --skip-jenkins flag to skip the prettify osascript calls which could fail due to permission issues in
-#           # CI environment.
-#           if ${{ inputs.legacy == true }}; then
-#             make -C src macvim-dmg-legacy
-#           else
-#             make -C src macvim-dmg
-#           fi
-# 
-#           if ${{ inputs.publish_postfix != '' }}; then
-#             mv src/MacVim/build/Release/MacVim.dmg src/MacVim/build/Release/MacVim${{ inputs.publish_postfix }}.dmg
-#           fi
-# 
-#       # Upload the dmg installer only when making tagged release or making a dev build from a master branch.
-#       # Note that this doesn't create a GitHub release for us, because we would prefer to do it manually, for two
-#       # reasons: 1) signing / notarization are currently done out of CI, 2) we want to manually format our release notes
-#       # and add pictures to make them look nice. 
-#       - name: Upload MacVim image
-#         if: inputs.publish && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master')
-#         uses: actions/upload-artifact@v4
-#         with:
-#           name: MacVim${{ inputs.publish_postfix  }}.dmg
-#           path: src/MacVim/build/Release/MacVim${{ inputs.publish_postfix }}.dmg
-# 
-#           # If doing a tagged release, use repository-specified number of retention days (usually 90 days) to make it
-#           # easier to audit. (specify "0" to indicate using repository settings)
-#           #
-#           # Otherwise, we are just doing a dev build for potential testing, just use a maximum of 21 days as we don't
-#           # tend to need these for long.
-#           retention-days: ${{ startsWith(github.ref, 'refs/tags/') && 0 || (github.retention_days > 21 && 21 || 0) }}
+      - name: Check Xcode project compatibility version
+        if: contains(matrix.extra, 'check-xcodeproj-compat')
+        run: |
+          # Confirm that the compatibility version of xcodeproj is correct and not outdated.
+          rm -rf src/MacVim/MacVim_xcode8.xcodeproj
+          make -C src macvim-xcodeproj-compat
+          if ! git diff --exit-code -- src/MacVim/MacVim_xcode8.xcodeproj; then
+            echo 'MacVim_xcode8.xcodeproj is outdated. Run "make -C src macvim-xcodeproj-compat" to re-generate it.'; false
+          fi
+
+      - name: Test MacVim
+        id: test_macvim
+        timeout-minutes: 10
+        run: |
+          make ${MAKE_BUILD_ARGS} -C src macvim-tests
+
+      - name: Upload failed MacVim test results
+        if: ${{ !cancelled() && failure() && steps.test_macvim.conclusion == 'failure' }}
+        uses: ./.github/actions/test_macvim_artifacts
+
+      - name: Build Vim test binaries
+        run: |
+          # Build the unit test binaries first. With link-time-optimization they take some time to link. Running them
+          # separately de-couples them from the timeout in tests, and allow us to build in parallel jobs (since tests
+          # can't run in parallel).
+          NPROC=$(getconf _NPROCESSORS_ONLN)
+
+          set -o verbose
+          make ${MAKE_BUILD_ARGS} -j${NPROC} -C src unittesttargets
+
+      - name: Test Vim
+        if: startsWith(github.ref, 'refs/tags/') || !matrix.testgui
+        timeout-minutes: 30
+        run: |
+          defaults delete org.vim.MacVim  # Clean up stale states
+          # Currently we don't run any non-src tests, as syntax tests are fragile and prone to spamming escape codes.
+          # This needs to be investigated and fixed upstream.
+          # MacVim is unlikely to introduce breaking changes in runtime files anyway.
+          make ${MAKE_BUILD_ARGS} -C src test
+
+      - name: Test Vim (GUI)
+        if: startsWith(github.ref, 'refs/tags/') || matrix.testgui
+        timeout-minutes: 30
+        run: |
+          defaults delete org.vim.MacVim  # Clean up stale states
+          make ${MAKE_BUILD_ARGS} -C src/testdir clean
+          make ${MAKE_BUILD_ARGS} -C src testgui
+
+      - name: Upload failed test files
+        if: ${{ !cancelled() && failure() }}
+        uses: ./.github/actions/test_artifacts
+
+      - name: Build MacVim dmg image
+        if: inputs.publish && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master')
+        run: |
+          # Use the --skip-jenkins flag to skip the prettify osascript calls which could fail due to permission issues in
+          # CI environment.
+          if ${{ inputs.legacy == true }}; then
+            make -C src macvim-dmg-legacy
+          else
+            make -C src macvim-dmg
+          fi
+
+          if ${{ inputs.publish_postfix != '' }}; then
+            mv src/MacVim/build/Release/MacVim.dmg src/MacVim/build/Release/MacVim${{ inputs.publish_postfix }}.dmg
+          fi
+
+      # Upload the dmg installer only when making tagged release or making a dev build from a master branch.
+      # Note that this doesn't create a GitHub release for us, because we would prefer to do it manually, for two
+      # reasons: 1) signing / notarization are currently done out of CI, 2) we want to manually format our release notes
+      # and add pictures to make them look nice. 
+      - name: Upload MacVim image
+        if: inputs.publish && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master')
+        uses: actions/upload-artifact@v4
+        with:
+          name: MacVim${{ inputs.publish_postfix  }}.dmg
+          path: src/MacVim/build/Release/MacVim${{ inputs.publish_postfix }}.dmg
+
+          # If doing a tagged release, use repository-specified number of retention days (usually 90 days) to make it
+          # easier to audit. (specify "0" to indicate using repository settings)
+          #
+          # Otherwise, we are just doing a dev build for potential testing, just use a maximum of 21 days as we don't
+          # tend to need these for long.
+          retention-days: ${{ startsWith(github.ref, 'refs/tags/') && 0 || (github.retention_days > 21 && 21 || 0) }}
